name: nutri_plate
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  salomon_bottom_bar: ^3.3.2
  flutter_screenutil: ^5.9.0
  table_calendar: ^3.1.1
  go_router: ^13.2.3
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter_bloc: ^8.1.5
  firebase_database: ^10.5.4
  firebase_storage: ^11.7.4
  bloc: ^8.1.4
  cloud_firestore: ^4.17.2
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.6.1
  image_picker: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.9
  build_test: ^2.2.2
  hive_generator: ^2.0.1
  get_it: ^7.7.0
  http: ^1.2.1
  dio: ^5.4.0
  animated_segmented_tab_control: ^2.0.0
  zego_uikit_prebuilt_call: ^4.14.3
  flutter_secure_storage: ^9.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/


  fonts:
    - family: TT Commons
      fonts:
        - asset: assets/fonts/tt-commons/TT Commons Regular.otf
          weight: 400
        - asset: assets/fonts/tt-commons/TT Commons Medium.otf
          weight: 500
        - asset: assets/fonts/tt-commons/TT Commons DemiBold.otf
          weight: 600
        - asset: assets/fonts/tt-commons/TT Commons Bold.otf
          weight: 600

